- name: Start beacon node
  hosts: beacon
  gather_facts: true
  serial: 20
  tasks:
    - name: Creates beacon dir
      file:
        path: "{{beacon_node_dir}}"
        state: directory
    - name: Modify permissions to match user-group inside docker image
      shell: chown -R "{{ beacon_user_id }}" "{{ beacon_node_dir }}"
      become: true
    - name: debug task
      debug:
        msg: "{{ beacon_start_args }}"
    - name: Start cl beacon node container
      docker_container:
        name: "{{ beacon_container_name }}"
        state: started
        image: "{{ beacon_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ beacon_require_restart | default(false) }}"
        volumes: "{{beacon_volumes}}"
        command: "{{ beacon_start_args }}"
        env: "{{ beacon_env | default({}) }}"
        user: "{{ beacon_user_id }}"
    - name: Get info on beacon container
      docker_container_info:
        name: "{{ beacon_container_name }}"
      register: container_result
    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if container_result.exists else 'does not exist' }}"
    - name: Print information about container
      debug:
        var: result.container
      when: container_result.exists

